dbt_bank:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 17 for SQL Server"
      server: host.docker.internal
      port: 1433
      database: DATN
      schema: dbo
      user: sa
      password: "123456"
      trusted_connection: false
      encrypt: false
      trust_cert: true
